services:  
  react-app:  
    build:  
      context: .  
      dockerfile: Dockerfile  
    ports:  
      - "80:80"  
  
  json-server:  
    build:  
      context: .  
      dockerfile: Dockerfile.json  
    ports:  
      - "3001:3001"